# Generated by Django 5.0.6 on 2024-07-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
